[package]
name = "base45"
version ="1.0.0"
authors = ["Rickard Natt och Dag <rickard@hey.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
